<a href="https://colab.research.google.com/github/softtechi007/skillfyme-python-assignment/blob/main/Python_Practical_Workflows_and_Collaboration_Strategies_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Problem Statement-1:**
Create a Student Grading System that calculates and displays grades based on marks entered by the user.

**Task**

1. Ask the user to input their name and marks for 3 subjects.
2. Calculate the average of the three marks.
3. Use conditional statements to determine the grade:
   - Average >= 90: **Grade A**
   - Average >= 75 and < 90: **Grade B**
   - Average >= 60 and < 75: **Grade C**
   - Average < 60: **Grade D**
4. Print the result using formatted output.

In [ ]:
def take_num_of_subjects():
  try:
      num_sub = int(input("Enter the number of subjects that you want to enter: "))

      if num_sub <= 0:
          print("Number of subjects cannot be zero or negative.")
          num_sub = 3
      else:
          print(f"Number of subjects set to: {num_sub}")

  except ValueError:
      print("Invalid input! You did not enter a valid number.")
      print("Default number of subjects is configured to 3.")
      num_sub = 3
  except:
      print("Unexpected error!")
      num_sub = 3
  return num_sub

def get_subject_mark(subject_number, max_mark=100):
    while True:
        try:
            mark = int(input(f"Enter marks for Subject {subject_number}: "))

            if mark < 0:
                print("Marks cannot be negative.")
            elif mark > max_mark:
                print(f"Marks cannot be more than {max_mark}.")
            else:
                return mark

        except ValueError:
            print("Invalid input! Please enter a valid number.")

def calculate_avg_marks(marks):
    avg_marks = sum(marks) / len(marks)
    if(avg_marks >= 90):
        grade = "A"
    elif (avg_marks >= 75 and avg_marks < 90):
        grade = "B"
    elif (avg_marks >= 60 and avg_marks < 75):
        grade = "C"
    else:
        grade = "D"
    return avg_marks, grade


name_user = input("Enter your name: ")
number_of_subjects = take_num_of_subjects()
marks = []

for i in range(number_of_subjects):
    mark = get_subject_mark(i+1,100)
    marks.append(mark)

average_marks, grade = calculate_avg_marks(marks)

print(f"{name_user} has got average mark of {round(average_marks, 2)} for {number_of_subjects} subjects and his final Grade is {grade}")




Enter your name: Iqbal
Enter the number of subjects that you want to enter: 3
Number of subjects set to: 3
Enter marks for Subject 1: 89
Enter marks for Subject 2: 90
Enter marks for Subject 3: 95
Iqbal has got average mark of 91.33 for 3 subjects and his final Grade is A


# Python – Practical Workflows and Collaboration Strategies – Part 1

## Assignment #1  
### Real-World Logic Systems: Smart Grading & Intelligent

---

### Problem Statement-2:

You're working as a developer for a **parking management system** at a mall. Your task is to create a **dynamic rate calculator** for cars entering the lot. The lot has the following rules:

1. Vehicles are charged based on parking duration:
   - First 2 hours: ₹20/hour
   - Next 3 hours: ₹15/hour
   - Remaining time: ₹10/hour

2. Mall operates from **6 AM to 12 AM (midnight)**.

3. If a vehicle is parked **before 6 AM or after 12 AM**, the system should reject the entry.

4. Use a loop to allow continuous data entry for multiple vehicles.

5. For every 5th vehicle, offer a 50% discount.

6. Break the loop if the user types `exit`.

---

### Task:

- Write a program to take **entry** and **exit time (in 24-hour format)**.
- Validate times and calculate the total amount due.
- Keep track of the number of vehicles and apply the discount logic.
- Print a summary of each vehicle's charge and a final report at the end.

---



In [ ]:
from datetime import datetime
import re

def calculate_parking_rate(hours):
    if hours <= 0:
        return "Invalid time: Hours must be positive"

    if hours <= 2:
        rate = hours * 20
    elif hours <= 5:
        rate = (2 * 20) + (hours - 2) * 15
    else:
        rate = (2 * 20) + (3 * 15) + (hours - 5) * 10

    return rate

def ask_more_vehicles():
    while True:
        response = input("Do you have more vehicles? (yes/no): ").strip()

        # Regex pattern: accepts yes, y, no, n (case insensitive)
        if re.match(r'^(y|yes|n|no)$', response, re.IGNORECASE):
            # Return True for yes, False for no
            return re.match(r'^(y|yes)$', response, re.IGNORECASE) is not None
        else:
            print("Invalid input! Please enter 'yes', 'y', 'no', or 'n'.")

def get_entry_exit():
    """Get valid entry and exit time with strict business hour rules"""

    # ================== ENTRY TIME ==================
    while True:
        try:
            entry_input = input("\nEnter Entry Hour (6 to 23): ").strip()
            entry_hour = int(entry_input)

            if entry_hour < 6 or entry_hour > 23:
                print(" Parking is NOT allowed before 6 AM or after 12 AM (23:00).")
                print("Please enter a time between 6 and 23.")
            else:
                entry_str = f"{entry_hour:02d}:00:00"
                print(f" Entry Time: {entry_str}")
                break

        except ValueError:
            print(" Please enter a valid number!")

    # ================== EXIT TIME ==================
    while True:
        try:
            exit_input = input("Enter Exit Hour (6 to 23): ").strip()
            exit_hour = int(exit_input)

            if exit_hour < 6 or exit_hour > 23:
                print(" Invalid hour! Please enter between 0 and 23.")
                continue

            # Check if exit is before entry (overnight parking)
            if exit_hour <= entry_hour:
                print("  Exit time is before entry time → Assuming next day parking.")
                duration = (24 - entry_hour) + exit_hour
            else:
                duration = exit_hour - entry_hour

            if duration <= 0:
                print("Exit time must be after entry time!")
                continue

            exit_str = f"{exit_hour:02d}:00:00"
            print(f" Exit Time : {exit_str}")
            print(f" Duration: {duration} hours")
            break

        except ValueError:
            print("Please enter a valid number!")

    return entry_hour, exit_hour, duration


# ===================== MAIN =====================
vehicle_list = []
vehicle_count = 0

while True:
    vehicle_count += 1
    print(f"\n Processing Vehicle {vehicle_count}")

    entry_time, exit_time, hours_spent = get_entry_exit()

    original_price = calculate_parking_rate(hours_spent)

    is_discounted = (vehicle_count % 5 == 0)

    if is_discounted:
        discount_amount = original_price * 0.5
        final_price = original_price - discount_amount
        print("50% Discount Applied!")
    else:
        discount_amount = 0
        final_price = original_price

    vehicle_list.append({
    "count": vehicle_count,
    "entry": entry_time,
    "exit": exit_time,
    "hours": hours_spent,
    "original_price": original_price,
    "discount_amount": discount_amount,
    "final_price": final_price,
    "discounted": is_discounted
    })

    if not ask_more_vehicles():
        break


# Final Summary
print("\n" + "="*70)
print("              PARKING MANAGEMENT SUMMARY")
print("="*70)

for v in vehicle_list:
    print(f"""
 Vehicle Number       : {v['count']}
 Entry Time           : {v['entry']:02d}:00
 Exit Time            : {v['exit']:02d}:00
 Total Hours Parked  : {v['hours']} hours

 Original Parking Fee : ₹{v['original_price']:.2f}
 Discount Applied     : {"Yes (50%)" if v['discounted'] else "No"}
 Discount Amount      : ₹{v['discount_amount']:.2f}
 Final Amount         : ₹{v['final_price']:.2f}

{"-"*70}
""")



 Processing Vehicle 1

Enter Entry Hour (6 to 23): 6
 Entry Time: 06:00:00
Enter Exit Hour (0 to 23): 6
  Exit time is before entry time → Assuming next day parking.
 Exit Time : 06:00:00
 Duration: 24 hours
Do you have more vehicles? (yes/no): y

 Processing Vehicle 2

Enter Entry Hour (6 to 23): 22
 Entry Time: 22:00:00
Enter Exit Hour (0 to 23): 0
  Exit time is before entry time → Assuming next day parking.
 Exit Time : 00:00:00
 Duration: 2 hours
Do you have more vehicles? (yes/no): 3
Invalid input! Please enter 'yes', 'y', 'no', or 'n'.
Do you have more vehicles? (yes/no): y

 Processing Vehicle 3

Enter Entry Hour (6 to 23): 3
 Parking is NOT allowed before 6 AM or after 12 AM (23:00).
Please enter a time between 6 and 23.

Enter Entry Hour (6 to 23): 5
 Parking is NOT allowed before 6 AM or after 12 AM (23:00).
Please enter a time between 6 and 23.

Enter Entry Hour (6 to 23): 7
 Entry Time: 07:00:00
Enter Exit Hour (0 to 23): 9
 Exit Time : 09:00:00
 Duration: 2 hours
Do you 

# Python – Practical Workflows and Collaboration Strategies – Part 1

## Assignment #2  
### Smart Systems in Python: Library & Booking

---

### Problem Statement–1:  
Build a **Library Management System** using lists, tuples, and dictionaries.

---

### Task:

1. Create a list of book titles available in a library.

2. Store book info as a dictionary with title, author, and year as keys.

3. Allow the user to:  
   - Search for a book by title  
   - Add a new book to the collection  
   - Display all books using a loop

4. Use a list comprehension to return books published after a given year.

---


In [ ]:
# ====================== LIBRARY MANAGEMENT SYSTEM ======================

# 1. List of book titles
book_titles = ["The Alchemist", "Harry Potter", "The Da Vinci Code",
               "1984", "To Kill a Mockingbird", "Pride and Prejudice"]

# 2. List of dictionaries to store complete book information
books = [
    {"title": "The Alchemist", "author": "Paulo Coelho", "year": 1988},
    {"title": "Harry Potter", "author": "J.K. Rowling", "year": 1997},
    {"title": "The Da Vinci Code", "author": "Dan Brown", "year": 2003},
    {"title": "1984", "author": "George Orwell", "year": 1949},
    {"title": "To Kill a Mockingbird", "author": "Harper Lee", "year": 1960},
    {"title": "Pride and Prejudice", "author": "Jane Austen", "year": 1813}
]

# Function to display all books
def display_all_books():
    print("\n--- All Books in Library ---")
    for book in books:
        print(f"Title : {book['title']}")
        print(f"Author: {book['author']}")
        print(f"Year  : {book['year']}")
        print("-" * 40)

# Function to search book by title
def search_book(title):
    found = False
    for book in books:
        if book['title'].lower() == title.lower():
            print("\n Book Found!")
            print(f"Title : {book['title']}")
            print(f"Author: {book['author']}")
            print(f"Year  : {book['year']}")
            print("-" * 40)
            found = True
            # You can break if you want only first match
    if not found:
        print(f"\n Book '{title}' not found!")

# Function to add a new book
def add_new_book():
    print("\n--- Add New Book ---")
    title = input("Enter Book Title: ").strip()
    author = input("Enter Author Name: ").strip()
    while True:
      try:
          year = int(input("Enter Publication Year: ").strip())
          break
      except ValueError:
          print("Invalid year! Please enter a number.")

    new_book = {"title": title, "author": author, "year": year}
    books.append(new_book)
    book_titles.append(title)
    print(f"Book '{title}' added successfully!")

# Function to get books after a certain year using List Comprehension
def books_after_year(given_year):
    recent_books = [book for book in books if book['year'] > given_year]
    return recent_books

def check_valid_year_entry():
  while True:
    try:
      input_year = int(input("Enter year: ").strip())
      return input_year
    except ValueError:
      print("Please enter a valid year!")

# ====================== MAIN MENU ======================

def main():
    while True:
        print("\n" + "="*50)
        print("LIBRARY MANAGEMENT SYSTEM")
        print("="*50)
        print("1. Display All Books")
        print("2. Search Book by Title")
        print("3. Add New Book")
        print("4. Show Books Published After a Year")
        print("5. Exit")

        choice = input("\nEnter your choice (1-5): ").strip()

        if choice == '1':
            display_all_books()

        elif choice == '2':
            title = input("Enter book title to search: ").strip()
            search_book(title)

        elif choice == '3':
            add_new_book()

        elif choice == '4':
            try:
                year = check_valid_year_entry()
                recent = books_after_year(year)
                print(f"\nBooks published after {year}:")
                if recent:
                    for book in recent:
                        print(f"- {book['title']} by {book['author']} ({book['year']})")
                else:
                    print("No books found after this year.")
            except ValueError:
                print("Please enter a valid year!")

        elif choice == '5':
            print("Thank you for using Library Management System! 👋")
            break

        else:
            print("Invalid choice! Please enter 1 to 5.")

# Run the program
if __name__ == "__main__":
    main()


LIBRARY MANAGEMENT SYSTEM
1. Display All Books
2. Search Book by Title
3. Add New Book
4. Show Books Published After a Year
5. Exit

Enter your choice (1-5): 4
Enter year: hjksaad
Please enter a valid year!
Enter year: 89.002
Please enter a valid year!
Enter year: 2000

Books published after 2000:
- The Da Vinci Code by Dan Brown (2003)

LIBRARY MANAGEMENT SYSTEM
1. Display All Books
2. Search Book by Title
3. Add New Book
4. Show Books Published After a Year
5. Exit

Enter your choice (1-5): 5
Thank you for using Library Management System! 👋


# Python - Practical Workflows and Collaboration Strategies - Part 1

## Assignment #2  
### Smart Systems in Python: Library & Booking

---

### Problem Statement-2:

You're building a **conference room booking system**. Each room can be booked by multiple users as long as the time slots don't overlap. A request includes:

- Room Name  
- User Name  
- Start Time  
- End Time  

---

### Task:

- Store bookings in a **dictionary of lists**, where each key is a room, and the value is a list of tuples: `(user, start_time, end_time)`.

- When a new booking is attempted, check for **time conflicts** in that room.

- If there's no conflict, add the booking.

- Display the full schedule at the end.

---

In [ ]:
# ====================== CONFERENCE ROOM BOOKING SYSTEM ======================

book_room_names = ["Room_1", "Room_2", "Room_3", "Room_4"]

booking_slots_info = {
    'room_1': [("Alice", 10, 12), ("Bob", 14, 16)],
    'room_2': [("Alice", 19, 24), ("Bob", 12, 16)],
    'room_3': [("Alice", 10, 12), ("Bob", 14, 16)],
    'room_4': [("Alice", 10, 12), ("Bob", 14, 16)],
}


def normalize_room(room):
    """Convert room name to dictionary key format"""
    return room.lower().replace(" ", "_")


def display_all_schedules():
    print("\n" + "="*60)
    print("ALL CURRENT BOOKINGS")
    print("="*60)
    for room in book_room_names:
        room_key = normalize_room(room)
        print(f"\n {room}")
        print("-" * 40)
        if not booking_slots_info.get(room_key):
            print("   No bookings yet.")
        else:
            for slot in booking_slots_info[room_key]:
                print(f" User : {slot[0]}")
                print(f" Time : {slot[1]:02d}:00 - {slot[2]:02d}:00")
        print("="*40)


def get_available_slots(room):
    """Returns list of available time ranges"""
    room_key = normalize_room(room)
    booked = set()

    for _, start, end in booking_slots_info.get(room_key, []):
        for h in range(start, end):
            booked.add(h)

    available = []
    start = None
    for h in range(24):
        if h not in booked:
            if start is None:
                start = h
        else:
            if start is not None:
                available.append((start, h))
                start = None
    if start is not None:
        available.append((start, 24))

    return available


def has_conflict(room, new_start, new_end):
    """Check if new booking overlaps with existing ones"""
    room_key = normalize_room(room)
    for _, start, end in booking_slots_info.get(room_key, []):
        if new_start < end and new_end > start:
            return True
    return False


def add_new_slot_for_room():
    print("\n--- Available Rooms ---")
    for i, room in enumerate(book_room_names, 1):
        print(f"{i}. {room}")

    # Select Room
    while True:
        try:
            choice = int(input("\nEnter the room number you want: ").strip())
            if 1 <= choice <= len(book_room_names):
                room = book_room_names[choice - 1]
                break
            else:
                print(" Invalid room number!")
        except ValueError:
            print(" Please enter a valid number!")

    name_of_user = input("Enter your name: ").strip()

    # Keep asking until valid booking is made
    while True:
        try:
            start_time = int(input("Enter Start Time (0-23): ").strip())
            end_time = int(input("Enter End Time (0-23): ").strip())

            if start_time >= end_time:
                print(" End time must be after start time!")
                continue
            if not (0 <= start_time < 24 and 0 <= end_time <= 24):
                print(" Times must be between 0 and 24!")
                continue

            # Check for conflict
            if has_conflict(room, start_time, end_time):
                print(f"\n Conflict detected in {room}!")
                print("Available slots are:")
                free_slots = get_available_slots(room)
                for s, e in free_slots:
                    if e - s >= 1:
                        print(f"   → {s:02d}:00 to {e:02d}:00")
                print("\nPlease try again with a different time.\n")
                continue
            else:
                # Book the slot
                room_key = normalize_room(room)
                booking_slots_info[room_key].append((name_of_user, start_time, end_time))
                booking_slots_info[room_key].sort(key=lambda x: x[1])

                print(f"\n Booking Successful!")
                print(f"Room : {room}")
                print(f"User : {name_of_user}")
                print(f"Time : {start_time:02d}:00 - {end_time:02d}:00")
                break

        except ValueError:
            print(" Please enter valid numbers for time!")


def main():
    while True:
        print("\n" + "="*55)
        print("CONFERENCE ROOM BOOKING SYSTEM")
        print("="*55)
        print("1. Display All Current Schedules")
        print("2. Check Available Slots")
        print("3. Book a New Slot")
        print("4. Exit")

        choice = input("\nEnter your choice (1-4): ").strip()

        if choice == '1':
            display_all_schedules()

        elif choice == '2':
            for i, room in enumerate(book_room_names, 1):
                print(f"{i}. {room}")
            try:
                room_choice = int(input("\nEnter room number to check availability: "))
                if 1 <= room_choice <= len(book_room_names):
                    room = book_room_names[room_choice - 1]
                    print(f"\nAvailable slots in {room}:")
                    free_slots = get_available_slots(room)
                    for s, e in free_slots:
                        if e - s >= 1:
                            print(f"   → {s:02d}:00 to {e:02d}:00")
                else:
                    print("Invalid room number!")
            except ValueError:
                print("Please enter a valid number!")

        elif choice == '3':
            add_new_slot_for_room()

        elif choice == '4':
            print("Thank you for using Conference Room Booking System! 👋")
            break

        else:
            print(" Invalid choice! Please enter 1 to 4.")


# Run the program
if __name__ == "__main__":
    main()


CONFERENCE ROOM BOOKING SYSTEM
1. Display All Current Schedules
2. Check Available Slots
3. Book a New Slot
4. Exit

Enter your choice (1-4): 1

ALL CURRENT BOOKINGS

 Room_1
----------------------------------------
 User : Alice
 Time : 10:00 - 12:00
 User : Bob
 Time : 14:00 - 16:00

 Room_2
----------------------------------------
 User : Alice
 Time : 19:00 - 24:00
 User : Bob
 Time : 12:00 - 16:00

 Room_3
----------------------------------------
 User : Alice
 Time : 10:00 - 12:00
 User : Bob
 Time : 14:00 - 16:00

 Room_4
----------------------------------------
 User : Alice
 Time : 10:00 - 12:00
 User : Bob
 Time : 14:00 - 16:00

CONFERENCE ROOM BOOKING SYSTEM
1. Display All Current Schedules
2. Check Available Slots
3. Book a New Slot
4. Exit

Enter your choice (1-4): 2
1. Room_1
2. Room_2
3. Room_3
4. Room_4

Enter room number to check availability: 1

Available slots in Room_1:
   → 00:00 to 10:00
   → 12:00 to 14:00
   → 16:00 to 24:00

CONFERENCE ROOM BOOKING SYSTEM
1. D

# Python – Practical Workflows and Collaboration Strategies – Part 1

## Assignment #3  
### Climate Analytics with NumPy: From Weekly Snapshots to Yearlong Trends

---

### Problem Statement–1:  
Simulate and analyze **temperature data** for a week using NumPy.

---

### Task:

1. Generate a 7-day temperature dataset for 3 cities (shape: 3×7) using `numpy.random.randint`.

2. Calculate:
   - Average temperature per city
   - Maximum temperature of the week
   - Temperature difference between city 1 and city 2 (element-wise)

3. Reshape the data to display day-wise temperatures using `reshape()`.

---



In [ ]:
import numpy as np

np.random.seed(42)

def generate_temperature(num_cities, no_of_week_days):
    # Generate 2D array: (cities, days)
    temps = np.random.randint(-5, 46, size=(num_cities, no_of_week_days))
    print(temps)
    print()
    temp_info = {}
    print("=== Temperature Data Generated ===\n")
    for i in range(num_cities):
        temp_info[f"City_{i+1}"] = temps[i]
        print(f"Temperatures for City_{i+1}:")
        print(temps[i])
        print("-" * 40)

    return temps, temp_info


def average_temperature(temps_2d):
    """Calculate average temperature for each city"""
    averages = np.mean(temps_2d, axis=1)   # axis=1 works on 2D array
    print("\n=== Average Temperature per City ===\n")
    for i, avg in enumerate(averages, 1):
        print(f"City_{i} Average: {avg:.2f}°C")
    return averages


def max_temperature(temps_2d):
    """Maximum temperature overall and per city"""
    print("\n=== Maximum Temperatures ===\n")
    print(f"Overall Max Temperature: {np.max(temps_2d)}°C")
    max_per_city = np.max(temps_2d, axis=1)
    for i, m in enumerate(max_per_city, 1):
        print(f"City_{i} Max: {m}°C")

def reverse_the_array_created(temps_2d):
    print("Original Temperature Array (Cities x Days):")
    print(temps_2d)
    print("-" * 50)

    # Reshape to (Days, Cities)
    reshaped_array = temps_2d.reshape(temps_2d.shape[1], temps_2d.shape[0])
    # Alternative: reshaped_array = temps_2d.T   ← This is simpler!

    print("Reshaped Array (Days x Cities):")
    print(reshaped_array)
    print("-" * 50)

    print(" Day-wise Temperature Report:\n")

    # Dynamic and Beautiful Printing
    for day, row in enumerate(reshaped_array, 1):
        print(f"Day {day}:")
        print(f"   City1 = {row[0]:2d}°C")
        print(f"   City2 = {row[1]:2d}°C")
        print(f"   City3 = {row[2]:2d}°C")
        print("-" * 30)

# ====================== Run the Program ======================

temps, temp_info = generate_temperature(3, 7)

average_temperature(temps)      # Pass the 2D array instead of dictionary
max_temperature(temps)




# Bonus: Difference between City 1 and City 2 (element-wise)
print("\n=== Temperature Difference (City 1 - City 2) ===\n")
diff = abs(temps[0] - temps[1])
print(f"{diff}\n")
reverse_the_array_created(temps)

[[33 23  9 37  2 15 33]
 [13 17  5  5 18 30 34]
 [18 -3 16 -4 18 38 24]]

=== Temperature Data Generated ===

Temperatures for City_1:
[33 23  9 37  2 15 33]
----------------------------------------
Temperatures for City_2:
[13 17  5  5 18 30 34]
----------------------------------------
Temperatures for City_3:
[18 -3 16 -4 18 38 24]
----------------------------------------

=== Average Temperature per City ===

City_1 Average: 21.71°C
City_2 Average: 17.43°C
City_3 Average: 15.29°C

=== Maximum Temperatures ===

Overall Max Temperature: 38°C
City_1 Max: 37°C
City_2 Max: 34°C
City_3 Max: 38°C

=== Temperature Difference (City 1 - City 2) ===

[20  6  4 32 16 15  1]

Original Temperature Array (Cities x Days):
[[33 23  9 37  2 15 33]
 [13 17  5  5 18 30 34]
 [18 -3 16 -4 18 38 24]]
--------------------------------------------------
Reshaped Array (Days x Cities):
[[33 23  9]
 [37  2 15]
 [33 13 17]
 [ 5  5 18]
 [30 34 18]
 [-3 16 -4]
 [18 38 24]]
----------------------------------------

# Assignment #3  
## Climate Analytics with NumPy: From Weekly Snapshots to Yearlong Trends

### Problem Statement - 2

You are part of a climate research team studying **temperature patterns** over 3 cities for a year (365 days).

You are provided with a simulated dataset with temperatures ranging from **-5°C to 45°C**.

---

# Task

## 1. Generate Dataset

Generate a NumPy array of shape `(3, 365)` representing daily temperatures for 3 cities.

---

## 2. Calculate the Following

### • Heatwave Days
Find the number of **heatwave days** for each city.

Condition:
- Temperature > 40°C

---

### • Hottest Day
Find:
- Maximum temperature recorded
- Which city it occurred in
- Which day it occurred on

---

### • Most Stable Climate
Find the city with the **most stable climate**.

Condition:
- Lowest standard deviation

---

## 3. Temperature Conversion

Convert all temperature values from **Celsius to Fahrenheit** using **NumPy broadcasting**.

Formula:

F = (C × 9/5) + 32

---

## 4. Top 5 Hottest Days

Display the:

- Temperature
- City
- Day

for the **top 5 hottest days** across all cities.

In [ ]:
import numpy as np
np.random.seed(42)

def generate_temperature(num_cities, no_of_week_days):
    # Generate 2D array: (cities, days)
    temps = np.random.randint(-5, 46, size=(num_cities, no_of_week_days))
    print(temps)
    print()
    temp_info = {}
    print("=== Temperature Data Generated ===\n")
    for i in range(num_cities):
        temp_info[f"City_{i+1}"] = temps[i]
        print(f"Temperatures for City_{i+1}:")
        print(temps[i])
        print("-" * 100)

    return temps, temp_info
def count_of_heatwave_days(temps_2d):
    """Count of heatwave days per city"""
    print("\n=== Heat Wave Days Per City ===\n")
    for i,temp in enumerate(temps_2d,1):
        heatwave_days = np.sum(temp > 40)
        print(f"City_{i} Heatwave Days: {heatwave_days}")

def max_temperature(temps_2d):
    """Maximum temperature overall and per city"""
    print("\n=== Maximum Temperatures ===\n")
    print(f"Hottest Day Temperature: {np.max(temps_2d)}°C")
    max_per_city = np.max(temps_2d, axis=1)
    for i, m in enumerate(max_per_city, 1):
        print(f"City_{i} Max: {m}°C")

def city_with_stable_climate(temps_2d):
    """City with the most stable climate"""
    print("\n=== Standard Deviation Temperatures ===\n")
    std_devs = np.std(temps_2d, axis=1)
    for i, m in enumerate(std_devs, 1):
        print(f"City_{i} standard_deviation_temperature: {m}°C")
    min_std_dev_index = np.argmin(std_devs)
    print(f"\nCity with the most stable climate: City_{min_std_dev_index+1}")

def change_to_farenheit(temps_2d):
    """Convert Degree Celsius to Farenheit temperature"""
    print("\n=== Temperature Conversion ===\n")
    fahrenheit_temps = (temps_2d * 9/5) + 32
    print(fahrenheit_temps)
    print("=== Temperature Data Generated ===\n")
    for i in range(len(fahrenheit_temps)):
        temp_info[f"City_{i+1}"] = fahrenheit_temps[i]
        print(f"Temperatures for City_{i+1}:")
        print(fahrenheit_temps[i])
        print("-" * 100)

    print("\n=== Top 5 Temperatures of Cities ===\n")

    for i in range(len(fahrenheit_temps)):

        # Indices of top 5 hottest days
        top_5_days = np.argsort(fahrenheit_temps[i])[-5:]

        print(f"\nCity_{i+1}")

        for day in top_5_days:
            temp = fahrenheit_temps[i][day]
            print(f"Day {day+1} --> {temp:.2f}°F")




temps, temp_info = generate_temperature(3, 365)
count_of_heatwave_days(temps)
max_temperature(temps)
city_with_stable_climate(temps)
change_to_farenheit (temps)

[[33 23  9 ... 43 11 38]
 [22 24 23 ... 29 13 14]
 [12 41 35 ... 38 -4  7]]

=== Temperature Data Generated ===

Temperatures for City_1:
[33 23  9 37  2 15 33 13 17  5  5 18 30 34 18 -3 16 -4 18 38 24 32 -4 15
 27  6 16 38 19 43 21 36 22 10  9 41 45 38 -3 31 45  1 15  3 33 12 -2 19
  8 44  3 20 -4 14 22 41  1 38  2 41 29  8 11 30 44 34 -2 -4  0 36 -2 23
 12 20 38 28  4 30  8 25 42  9  2  8 17 34 15 10 39 12 41 18 20 19 39 35
 23  9 39 -5 19  1  3 18 -5 38  2 18  5 45 11  2 29 29 27 -1 36 33 35 22
  1  3  2  6 28 27 42 17 18 31 29 38 34 16 21 29 -5 29 31 41  8 -3 -5 -1
 20  8 33 21  3  9  9 20 36  7 45 26 33 43 26 -2 24 31 17 33 39  9 37 23
 30  7 26  1 45 16 22 -4 36 39  0 22 22 38 38 14 24  5 22 19 33 27 -5 21
  7 35 -3 33  0  2 21  3 31 27 45 36 38 18  9 26 26 18 35 43 43  6 33 -4
 -3 43 31 43 11 43 -4 -4 22 17 31 26 27 -5 13 -4 38 20 26  0 26 -2  5 11
 32 18 -1 28  0 16  5 42 10 27  3  0 10 23 -3 14 30 13 20 -3 13 14 26  1
 35 27 34 33 12 34 -5  5 22 19 44 17 25 24 36 29  1 10 20 4

# Assignment #4: Data Dissection — Real-World Data Cleaning & Analysis with Pandas

## Problem Statement 1

Perform data cleaning and analysis on a CSV file containing customer order data.

### Tasks

1. Load a CSV file with columns: `CustomerID`, `OrderAmount`, `OrderDate`, `Region`.
2. Display basic info (`.info()` and `.describe()`).
3. Drop rows with missing `OrderAmount`.
4. Filter and show customers from a specific region (e.g., `'North'`).
5. Sort data by `OrderAmount` descending.
6. Calculate average order value per region using `groupby`.

In [ ]:
import pandas as pd
from io import StringIO

data = """CustomerID,OrderAmount,OrderDate,Region
CUST1001,250.75,2024-01-15,North
CUST1002,,2024-01-16,East
CUST1003,89.99,2024-01-16,South
CUST1004,450.00,2024-01-17,West
CUST1005,125.50,2024-01-18,North
CUST1006,,2024-01-19,North
CUST1007,310.25,2024-01-20,East
CUST1008,99.99,2024-01-21,South
CUST1009,675.30,2024-01-22,West
CUST1010,45.00,2024-01-23,North
CUST1011,189.99,2024-01-24,East
CUST1012,,2024-01-25,South
CUST1013,520.75,2024-01-26,West
CUST1014,75.25,2024-01-27,North
CUST1015,340.00,2024-01-28,East
CUST1016,210.50,2024-01-29,South
CUST1017,890.00,2024-01-30,West
CUST1018,64.99,2024-01-31,North
CUST1019,430.25,2024-02-01,East
CUST1020,,2024-02-02,West
CUST1021,150.00,2024-02-03,South
CUST1022,725.40,2024-02-04,North
CUST1023,95.50,2024-02-05,East
CUST1024,285.75,2024-02-06,West
CUST1025,330.00,2024-02-07,South"""

df = pd.read_csv(StringIO(data))
df.to_csv('customer_orders.csv', index=False)
print("✅ File 'customer_orders.csv' created successfully!")

✅ File 'customer_orders.csv' created successfully!


In [ ]:
df.head()

,CustomerID,OrderAmount,OrderDate,Region
0,CUST1001,250.75,2024-01-15,North
1,CUST1002,NaN,2024-01-16,East
2,CUST1003,89.99,2024-01-16,South
3,CUST1004,450.00,2024-01-17,West
4,CUST1005,125.50,2024-01-18,North


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   CustomerID   25 non-null     object 
 1   OrderAmount  21 non-null     float64
 2   OrderDate    25 non-null     object 
 3   Region       25 non-null     object 
dtypes: float64(1), object(3)
memory usage: 932.0+ bytes


In [ ]:
df.describe()

,OrderAmount
count,21.000000
mean,302.626667
std,238.008202
min,45.000000
25%,99.990000
50%,250.750000
75%,430.250000
max,890.000000


In [ ]:
df.describe(include='all')

,CustomerID,OrderAmount,OrderDate,Region
count,25,21.000000,25,25
unique,25,NaN,24,4
top,CUST1001,NaN,2024-01-16,North
freq,1,NaN,2,7
mean,NaN,302.626667,NaN,NaN
std,NaN,238.008202,NaN,NaN
min,NaN,45.000000,NaN,NaN
25%,NaN,99.990000,NaN,NaN
50%,NaN,250.750000,NaN,NaN
75%,NaN,430.250000,NaN,NaN


In [ ]:
df.dropna()

,CustomerID,OrderAmount,OrderDate,Region
0,CUST1001,250.75,2024-01-15,North
2,CUST1003,89.99,2024-01-16,South
3,CUST1004,450.00,2024-01-17,West
4,CUST1005,125.50,2024-01-18,North
6,CUST1007,310.25,2024-01-20,East
7,CUST1008,99.99,2024-01-21,South
8,CUST1009,675.30,2024-01-22,West
9,CUST1010,45.00,2024-01-23,North
10,CUST1011,189.99,2024-01-24,East
12,CUST1013,520.75,2024-01-26,West


In [ ]:
df[df['Region'] == 'North']

,CustomerID,OrderAmount,OrderDate,Region
0,CUST1001,250.75,2024-01-15,North
4,CUST1005,125.50,2024-01-18,North
5,CUST1006,NaN,2024-01-19,North
9,CUST1010,45.00,2024-01-23,North
13,CUST1014,75.25,2024-01-27,North
17,CUST1018,64.99,2024-01-31,North
21,CUST1022,725.40,2024-02-04,North


In [ ]:
df.sort_values(by='OrderAmount', ascending=False)

,CustomerID,OrderAmount,OrderDate,Region
16,CUST1017,890.00,2024-01-30,West
21,CUST1022,725.40,2024-02-04,North
8,CUST1009,675.30,2024-01-22,West
12,CUST1013,520.75,2024-01-26,West
3,CUST1004,450.00,2024-01-17,West
18,CUST1019,430.25,2024-02-01,East
14,CUST1015,340.00,2024-01-28,East
24,CUST1025,330.00,2024-02-07,South
6,CUST1007,310.25,2024-01-20,East
23,CUST1024,285.75,2024-02-06,West


In [ ]:
df_new = df.groupby('Region')['OrderAmount'].mean()
df_new

,OrderAmount
Region,
East,273.198000
North,214.481667
South,176.096000
West,564.360000


# Python - Practical Workflows and Collaboration Strategies - Part 1

## Assignment #4  
### Data Dissection: Real-World Data Cleaning & Analysis with Pandas  

---

### Problem Statement-2:  
You're building a tool for analyzing flight delay data for a local airport.  
The dataset contains: FlightID, Airline, Destination, DepartureTime, DelayInMinutes  

---

### Task:  
1. Load the dataset and drop any rows with missing DelayInMinutes.  
2. Filter only the flights delayed over 30 minutes.  
3. Group by Airline and show:  
   - Total number of delayed flights  
   - Average delay time  
   - Identify the destination with the highest cumulative delay.  
4. Create a new column Severity:  
   - < 30 mins: "Low"  
   - 30–60 mins: "Medium"  
   - > 60 mins: "High"

In [ ]:
import pandas as pd
from io import StringIO

# Dataset as a string
data = """FlightID,Airline,Destination,DepartureTime,DelayInMinutes
FX101,Delta,New York,10:30,45
FX102,United,Boston,11:00,
FX103,Delta,Boston,11:45,15
FX104,JetBlue,Chicago,13:30,65
FX105,United,New York,15:00,80
FX106,JetBlue,Chicago,16:45,35"""

# Read the data into a DataFrame
df = pd.read_csv(StringIO(data))

# Display original dataset
print("Original Dataset:")
print(df)

# Save to CSV file
df.to_csv('flight_delays.csv', index=False)
print("\n Dataset saved as 'flight_delays.csv'")

# Step 2: Load the dataset from CSV (optional - demonstrates loading)
df_loaded = pd.read_csv('flight_delays.csv')
print("\n Loaded from CSV:")
print(df_loaded)

Original Dataset:
  FlightID  Airline Destination DepartureTime  DelayInMinutes
0    FX101    Delta    New York         10:30            45.0
1    FX102   United      Boston         11:00             NaN
2    FX103    Delta      Boston         11:45            15.0
3    FX104  JetBlue     Chicago         13:30            65.0
4    FX105   United    New York         15:00            80.0
5    FX106  JetBlue     Chicago         16:45            35.0

 Dataset saved as 'flight_delays.csv'

 Loaded from CSV:
  FlightID  Airline Destination DepartureTime  DelayInMinutes
0    FX101    Delta    New York         10:30            45.0
1    FX102   United      Boston         11:00             NaN
2    FX103    Delta      Boston         11:45            15.0
3    FX104  JetBlue     Chicago         13:30            65.0
4    FX105   United    New York         15:00            80.0
5    FX106  JetBlue     Chicago         16:45            35.0


In [ ]:
# Step 3: Task 1 - Drop rows with missing DelayInMinutes
df_clean = df.dropna(subset=['DelayInMinutes'])
print("\n Task 1 - After dropping missing DelayInMinutes:")
print(df_clean)


 Task 1 - After dropping missing DelayInMinutes:
  FlightID  Airline Destination DepartureTime  DelayInMinutes
0    FX101    Delta    New York         10:30            45.0
2    FX103    Delta      Boston         11:45            15.0
3    FX104  JetBlue     Chicago         13:30            65.0
4    FX105   United    New York         15:00            80.0
5    FX106  JetBlue     Chicago         16:45            35.0


In [ ]:
df_delayed = df_clean[df_clean['DelayInMinutes'] > 30]
print("\n Task 2 - Flights Delayed Over 30 Minutes:")
print(df_delayed)


 Task 2 - Flights Delayed Over 30 Minutes:
  FlightID  Airline Destination DepartureTime  DelayInMinutes
0    FX101    Delta    New York         10:30            45.0
3    FX104  JetBlue     Chicago         13:30            65.0
4    FX105   United    New York         15:00            80.0
5    FX106  JetBlue     Chicago         16:45            35.0


In [ ]:
df_grouped = df_delayed.groupby('Airline').agg(
    Total_Delayed_Flights=('DelayInMinutes', 'count'),
    Average_Delay_Time=('DelayInMinutes', 'mean')
).round(2)

print("\n Task 3 - Group by Airline Analysis:")
print(df_grouped)


 Task 3 - Group by Airline Analysis:
         Total_Delayed_Flights  Average_Delay_Time
Airline                                           
Delta                        1                45.0
JetBlue                      2                50.0
United                       1                80.0


In [ ]:
print(df_loaded)

  FlightID  Airline Destination DepartureTime  DelayInMinutes
0    FX101    Delta    New York         10:30            45.0
1    FX102   United      Boston         11:00             NaN
2    FX103    Delta      Boston         11:45            15.0
3    FX104  JetBlue     Chicago         13:30            65.0
4    FX105   United    New York         15:00            80.0
5    FX106  JetBlue     Chicago         16:45            35.0


In [ ]:
# Step 6: Task 3 (continued) - Destination with highest cumulative delay per airline
print("\n Task 6 - Destination with highest cumulative delay per airline:")
for airline in df_delayed['Airline'].unique():
    airline_data = df_delayed[df_delayed['Airline'] == airline]
    dest_delays = airline_data.groupby('Destination')['DelayInMinutes'].sum()
    top_dest = dest_delays.idxmax() if not dest_delays.empty else "None"
    top_delay = dest_delays.max() if not dest_delays.empty else 0
    print(f"  {airline}: {top_dest} (Total Delay: {top_delay} mins)")


 Task 6 - Destination with highest cumulative delay per airline:
  Delta: New York (Total Delay: 45.0 mins)
  JetBlue: Chicago (Total Delay: 100.0 mins)
  United: New York (Total Delay: 80.0 mins)


In [ ]:
# Step 7: Task 4 - Create Severity column
def classify_severity(minutes):
    if minutes < 30:
        return "Low"
    elif 30 <= minutes <= 60:
        return "Medium"
    else:
        return "High"

df_clean['Severity'] = df_clean['DelayInMinutes'].apply(classify_severity)
print("\n Task 4 - Dataset with Severity column:")
print(df_clean)


 Task 4 - Dataset with Severity column:
  FlightID  Airline Destination DepartureTime  DelayInMinutes Severity
0    FX101    Delta    New York         10:30            45.0   Medium
2    FX103    Delta      Boston         11:45            15.0      Low
3    FX104  JetBlue     Chicago         13:30            65.0     High
4    FX105   United    New York         15:00            80.0     High
5    FX106  JetBlue     Chicago         16:45            35.0   Medium


/tmp/ipykernel_1986/3199662246.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Severity'] = df_clean['DelayInMinutes'].apply(classify_severity)
